title: "DGGS: Scalable Geospatial Data Processing for EO"
author: Living Planet Symposium 2025 Demo Team
logo: null
language: en
only_build_toc_files: true

html:
  use_repository_button: true
  use_issues_button: true
  use_download_button: true

repository:
  url: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
  path_to_book: ""
  branch: main

launch_buttons:
  notebook_interface: jupyterlab
  thebe: true
