name: xdggs_demo
channels:
  - conda-forge
  - nodefaults

dependencies:
  - xarray
  - plotly
  - healpy
  - cartopy
  - shapely
  - sparse
  - fsspec
  - git
  - zarr=2.18.4
  - distributed
  - dask
  - hvplot
  - geopandas
  - s3fs
  - intake<2
  - intake-xarray<2
  - jupyterlab>=4.4
  - jupyterlab-git
  - dask-labextension
  - pip
  - pip:
      - xdggs
